import type { CodigoError } from '@/constants/codigos_error';

/**
 * Códigos de la familia de plataformas Midea descritos en el manual de aires.
 * El significado puede cambiar entre series: confirmar siempre contra el modelo.
 */
export const CODIGOS_AIRE_MANUAL: CodigoError[] = [
  {
    codigo: 'EC07',
    descripcion: 'Velocidad del ventilador DC exterior fuera de control',
    causas: ['Motor o ventilador DC exterior defectuoso o bloqueado', 'Conector o cableado del motor', 'Alimentación o realimentación anormal', 'PCB exterior o circuito de control del ventilador'],
    solucion: 'Apagar el equipo y verificar que el ventilador gire libremente. Inspeccionar conectores y cableado. Comprobar alimentación y señal del motor según el manual. Si motor y cableado son correctos, revisar la PCB exterior.',
    partes: ['Motor del ventilador exterior', 'PCB exterior'],
  },
  {
    codigo: 'EC51',
    descripcion: 'Error de EEPROM de la unidad exterior',
    causas: ['EEPROM o PCB exterior defectuosa', 'Fallo de alimentación o comunicación interna de la PCB', 'Datos de memoria corruptos'],
    solucion: 'Desenergizar y reiniciar según el tiempo indicado por el manual. Revisar alimentación y conectores de la PCB. Si el código permanece, confirmar la PCB correspondiente.',
    partes: ['EEPROM', 'PCB exterior'],
  },
  {
    codigo: 'EC52',
    descripcion: 'Sensor de temperatura de serpentín del condensador T3 abierto o en corto',
    causas: ['Sensor T3 abierto o cortocircuitado', 'Conector flojo u oxidado', 'Cableado dañado', 'PCB exterior'],
    solucion: 'Inspeccionar sensor y conector. Medir su resistencia y compararla con la tabla del modelo y la temperatura real. Comprobar la continuidad del cableado hasta la PCB.',
    partes: ['Sensor T3', 'PCB exterior'],
  },
  {
    codigo: 'EC53',
    descripcion: 'Sensor de temperatura ambiente exterior T4 abierto o en corto',
    causas: ['Sensor T4 defectuoso', 'Cableado o conector', 'PCB exterior'],
    solucion: 'Medir la resistencia del T4 a temperatura conocida y compararla con la curva especificada por Midea. Revisar continuidad y conectores.',
    partes: ['Sensor T4', 'PCB exterior'],
  },
  {
    codigo: 'EC54',
    descripcion: 'Sensor de temperatura de descarga del compresor TP abierto o en corto',
    causas: ['Sensor TP defectuoso', 'Sensor mal instalado sobre la tubería', 'Cableado o conector', 'PCB exterior'],
    solucion: 'Inspeccionar la posición y fijación del sensor. Medir su resistencia según la tabla del modelo y revisar el cableado hasta la PCB.',
    partes: ['Sensor TP', 'PCB exterior'],
  },
  {
    codigo: 'EC56',
    descripcion: 'Sensor T2B de la unidad exterior fuera de rango',
    causas: ['Sensor T2B', 'Conector o cableado', 'PCB exterior'],
    solucion: 'Inspeccionar la conexión, medir la resistencia y compararla con la tabla del modelo. Comprobar continuidad y revisar la PCB si la entrada permanece anormal.',
    partes: ['Sensor T2B', 'PCB exterior'],
  },
  {
    codigo: 'ECC1',
    descripcion: 'Otro sensor de refrigerante de unidad interior detecta fuga (multizona)',
    causas: ['Fuga real', 'Sensor de refrigerante defectuoso o fuera de calibración', 'Conexión del sensor', 'Circuito de control'],
    solucion: 'Ventilar y detener el equipo cuando el refrigerante pueda ser inflamable. Inspeccionar conexiones y circuito frigorífico, comprobar el sensor según el manual y buscar la fuga antes de recargar.',
    partes: ['Sensor de refrigerante', 'Material de reparación de fuga'],
  },
  {
    codigo: 'EH00',
    descripcion: 'Fallo EEPROM de la unidad interior',
    causas: ['EEPROM o PCB interior', 'Alimentación inestable', 'Fallo de memoria'],
    solucion: 'Desenergizar y reiniciar según el manual. Revisar alimentación y conectores. Si persiste, verificar la PCB interior.',
    partes: ['EEPROM', 'PCB interior'],
  },
  {
    codigo: 'EH02',
    descripcion: 'Error de detección de cruce por cero',
    causas: ['Alimentación anormal', 'Circuito de detección de la PCB', 'Conectores o cableado', 'PCB interior'],
    solucion: 'Medir la alimentación AC, revisar conexiones y comprobar el circuito de detección según el procedimiento de servicio.',
    partes: ['PCB interior', 'Filtro de línea'],
  },
  {
    codigo: 'EH03',
    descripcion: 'Velocidad del ventilador interior fuera de control',
    causas: ['Motor interior', 'Rodete bloqueado o sucio', 'Conector o cableado', 'Señal de realimentación', 'PCB'],
    solucion: 'Comprobar giro libre y suciedad, inspeccionar conectores y verificar alimentación y señal del motor según el modelo.',
    partes: ['Motor del ventilador interior', 'PCB interior'],
  },
  {
    codigo: 'EH0A',
    descripcion: 'Error de parámetros EEPROM de la unidad interior',
    causas: ['Datos EEPROM corruptos', 'PCB interior', 'Configuración incompatible'],
    solucion: 'Reiniciar, comprobar compatibilidad y configuración de la PCB, y consultar el procedimiento de actualización o reemplazo del modelo.',
    partes: ['EEPROM', 'PCB interior'],
  },
  {
    codigo: 'EH0B',
    descripcion: 'Error de comunicación entre PCB principal y display interior',
    causas: ['Cable de comunicación', 'Conectores', 'PCB principal', 'Tarjeta display'],
    solucion: 'Apagar y reiniciar, revisar cableado y conectores, y probar la PCB principal y el display según el flujo del modelo.',
    partes: ['Cable de comunicación', 'PCB principal', 'Tarjeta display'],
  },
  {
    codigo: 'EH3A',
    descripcion: 'Protección por tensión DC baja del módulo de ventilador externo',
    causas: ['Fuente o alimentación del módulo', 'Bus DC bajo', 'Cableado o conectores', 'Módulo o PCB del ventilador'],
    solucion: 'Verificar alimentación y conectores, medir el bus DC con el procedimiento seguro del fabricante e inspeccionar el módulo.',
    partes: ['Módulo de ventilador externo', 'PCB del ventilador'],
  },
  {
    codigo: 'EH3B',
    descripcion: 'Fallo por tensión DC alta del módulo de ventilador externo',
    causas: ['Fuente o rectificación anormal', 'Circuito de bus DC', 'PCB o módulo del ventilador'],
    solucion: 'Comprobar alimentación y bus DC con seguridad, revisar conectores y PCB. No manipular capacitores sin comprobar su descarga.',
    partes: ['Módulo de ventilador externo', 'PCB del ventilador'],
  },
  {
    codigo: 'EH3C',
    descripcion: 'Anomalía del módulo o motor de aire fresco o su realimentación',
    causas: ['Motor o módulo de aire fresco', 'Cableado o señal de realimentación', 'PCB'],
    solucion: 'Comprobar conectores, verificar funcionamiento y señal del módulo, y revisar la PCB si la señal es correcta.',
    partes: ['Módulo de aire fresco', 'PCB'],
  },
  {
    codigo: 'EH60',
    descripcion: 'Sensor de temperatura ambiente interior T1 abierto o en corto',
    causas: ['Sensor T1', 'Cableado o conector', 'PCB'],
    solucion: 'Medir la resistencia del T1 a temperatura conocida y compararla con la tabla del modelo. Comprobar continuidad y revisar la PCB si corresponde.',
    partes: ['Sensor T1', 'PCB interior'],
  },
  {
    codigo: 'EH61',
    descripcion: 'Sensor de temperatura de tubería o serpentín interior T2 abierto o en corto',
    causas: ['Sensor T2', 'Montaje del sensor', 'Cableado o conector', 'PCB'],
    solucion: 'Verificar la posición del sensor, medir su resistencia según la tabla del modelo y comprobar continuidad.',
    partes: ['Sensor T2', 'PCB interior'],
  },
  {
    codigo: 'EH62',
    descripcion: 'Anomalía del sensor o módulo de aire fresco o entrada de temperatura, según plataforma',
    causas: ['Sensor o módulo correspondiente', 'Cableado o conector', 'PCB'],
    solucion: 'Identificar el modelo exacto, consultar su tabla de códigos, inspeccionar conectores y medir el sensor o señal indicada.',
    partes: ['Sensor o módulo de aire fresco', 'PCB'],
  },
  {
    codigo: 'EHB3',
    descripcion: 'Fallo de comunicación entre controlador cableado y unidad principal',
    causas: ['Cableado del controlador', 'Conectores o polaridad', 'Controlador cableado', 'PCB interior'],
    solucion: 'Revisar continuidad, polaridad y conexiones. Comprobar alimentación del controlador y probar controlador o PCB según el procedimiento.',
    partes: ['Controlador cableado', 'Cableado', 'PCB interior'],
  },
  {
    codigo: 'EHBA',
    descripcion: 'Fallo de comunicación entre módulo de ventilador externo y unidad interior',
    causas: ['Cableado o señal del módulo', 'Motor o módulo externo', 'PCB interior o del módulo'],
    solucion: 'Inspeccionar conectores, verificar alimentación y señal de realimentación y comprobar el módulo del ventilador.',
    partes: ['Módulo de ventilador externo', 'PCB interior'],
  },
  {
    codigo: 'EHBE',
    descripcion: 'Error de comunicación entre radar y display o fallo del radar',
    causas: ['Cable de comunicación', 'Radar', 'Tarjeta display'],
    solucion: 'Revisar conectores y cableado, reiniciar según el manual y comprobar radar y display por separado.',
    partes: ['Radar', 'Tarjeta display', 'Cable de comunicación'],
  },
  {
    codigo: 'EHC1',
    descripcion: 'Sensor de refrigerante detecta fuga',
    causas: ['Fuga real', 'Sensor activado por concentración de refrigerante', 'Conexiones, serpentín o tubería', 'Fallo del sensor después de descartar fuga'],
    solucion: 'Detener el equipo y ventilar cuando corresponda. Buscar y reparar la fuga, comprobar sensor y conexiones y verificar estanqueidad antes de operar.',
    partes: ['Sensor de refrigerante', 'Material de reparación de fuga'],
  },
  {
    codigo: 'EHC2',
    descripcion: 'Sensor fuera de rango y además se detecta condición de fuga',
    causas: ['Fuga real', 'Sensor fuera de rango', 'Cableado o conector', 'PCB'],
    solucion: 'Tratar como evento de fuga, inspeccionar el circuito frigorífico, comprobar sensor y cableado y seguir el procedimiento del modelo.',
    partes: ['Sensor de refrigerante', 'Material de reparación de fuga', 'PCB'],
  },
  {
    codigo: 'EHC3',
    descripcion: 'Sensor de refrigerante fuera de rango',
    causas: ['Sensor defectuoso', 'Cableado o conector', 'PCB interior'],
    solucion: 'Revisar la conexión sensor-PCB, comprobar alimentación y señal según el manual y sustituir el sensor como prueba controlada.',
    partes: ['Sensor de refrigerante', 'PCB interior'],
  },
  {
    codigo: 'EL01',
    descripcion: 'Fallo de comunicación entre unidad interior y exterior',
    causas: ['Cable de comunicación', 'Polaridad o conexiones', 'Alimentación', 'PCB interior o exterior'],
    solucion: 'Desenergizar antes de intervenir, revisar cableado, terminales y continuidad, verificar alimentación de ambas unidades y comprobar las PCB.',
    partes: ['Cable de comunicación', 'PCB interior', 'PCB exterior'],
  },
  {
    codigo: 'EL0C',
    descripcion: 'Sistema con falta de refrigerante o detección de fuga',
    causas: ['Fuga', 'Carga insuficiente', 'Obstrucción o condición anormal similar', 'Sensor o algoritmo de detección'],
    solucion: 'Inspeccionar fugas, comprobar presiones y temperaturas según refrigerante y modelo, verificar carga por peso y revisar serpentines y flujo de aire.',
    partes: ['Refrigerante especificado', 'Filtro secante', 'Material de reparación de fuga'],
  },
  {
    codigo: 'FHCC',
    descripcion: 'Error del sensor de refrigerante',
    causas: ['Sensor', 'Cableado o conector', 'PCB'],
    solucion: 'Comprobar la conexión sensor-PCB, verificar alimentación y señal y probar el sensor según el manual.',
    partes: ['Sensor de refrigerante', 'PCB'],
  },
  {
    codigo: 'PC00',
    descripcion: 'Protección del módulo IPM o sobrecorriente IGBT',
    causas: ['IPM o IGBT', 'Compresor', 'Cableado del compresor', 'Ventilación o disipación térmica', 'PCB inverter'],
    solucion: 'Desenergizar y descargar capacitores antes de medir. Inspeccionar conexiones, aislamiento y bobinados del compresor y revisar IPM y disipador.',
    partes: ['IPM o IGBT', 'Compresor inverter', 'PCB inverter'],
  },
  {
    codigo: 'PC01',
    descripcion: 'Protección por tensión alta o baja',
    causas: ['Red eléctrica', 'Conexiones flojas', 'Fuente o rectificador', 'Bus DC', 'PCB inverter'],
    solucion: 'Medir la tensión de entrada con seguridad, revisar terminales y comprobar el bus DC según el manual. Si la alimentación es normal, diagnosticar la PCB inverter.',
    partes: ['Fuente o rectificador', 'PCB inverter'],
  },
  {
    codigo: 'PC02',
    descripcion: 'Protección por alta temperatura del compresor o IPM o condición de alta presión, según plataforma',
    causas: ['Falta de ventilación', 'Condensador sucio', 'Ventilador exterior', 'Sobrecarga de refrigerante', 'Restricción del circuito', 'Compresor sobrecalentado'],
    solucion: 'Verificar flujo de aire y limpieza del condensador, comprobar ventilador, medir temperaturas y presiones con el refrigerante correcto y revisar la protección térmica.',
    partes: ['Ventilador exterior', 'Compresor', 'PCB inverter'],
  },
  {
    codigo: 'PC03',
    descripcion: 'Protección de presión del sistema',
    causas: ['Fuga o carga insuficiente', 'Sobrecarga', 'Restricción', 'Flujo de aire insuficiente', 'Condiciones ambientales extremas', 'Compresor o válvula de expansión'],
    solucion: 'Medir la presión según refrigerante y modelo, comparar con las condiciones reales de operación y revisar temperaturas, flujo de aire, restricciones y fugas.',
    partes: ['Sensor de presión', 'Válvula de expansión', 'Filtro secante'],
  },
  {
    codigo: 'PC04',
    descripcion: 'Error del accionamiento inverter del compresor',
    causas: ['PCB inverter', 'IPM', 'Compresor', 'Cableado U/V/W', 'Alimentación DC'],
    solucion: 'Desenergizar y descargar capacitores. Revisar conexiones U/V/W, bobinados, aislamiento, IPM y PCB según el procedimiento.',
    partes: ['Compresor inverter', 'IPM', 'PCB inverter'],
  },
  {
    codigo: 'PC08',
    descripcion: 'Protección por sobrecorriente',
    causas: ['Compresor', 'IPM o inverter', 'Tensión anormal', 'Cableado', 'Carga mecánica o frigorífica anormal'],
    solucion: 'Medir corriente si es seguro, comprobar tensión, revisar compresor e IPM y buscar una condición frigorífica anormal.',
    partes: ['Compresor inverter', 'IPM', 'PCB inverter'],
  },
  {
    codigo: 'PC0L',
    descripcion: 'Protección por baja temperatura ambiente exterior',
    causas: ['Temperatura ambiente realmente muy baja', 'Sensor T4 incorrecto', 'Condiciones fuera de especificación'],
    solucion: 'Medir la temperatura ambiente, compararla con la lectura de T4 y verificar el sensor si la lectura es incorrecta.',
    partes: ['Sensor T4'],
  },
  {
    codigo: 'PC40',
    descripcion: 'Fallo de comunicación entre control principal exterior y circuito o driver del compresor',
    causas: ['Cableado o conectores', 'PCB principal', 'Driver o IPM', 'Alimentación del circuito'],
    solucion: 'Inspeccionar conectores, verificar alimentación del driver y comprobar las señales de comunicación según el manual.',
    partes: ['Driver o IPM', 'PCB exterior', 'Cableado'],
  },
  {
    codigo: 'AP',
    descripcion: 'Modo AP o configuración de conexión Wi‑Fi',
    causas: ['Modo de configuración de red activo'],
    solucion: 'No es una falla. Completar o cancelar la configuración Wi‑Fi siguiendo el manual del equipo.',
  },
  {
    codigo: 'CL',
    descripcion: 'Recordatorio de limpieza del filtro',
    causas: ['Mantenimiento programado'],
    solucion: 'No es una falla. Limpiar el filtro y reiniciar el recordatorio según el manual.',
    partes: ['Filtro de aire'],
  },
  {
    codigo: 'DF',
    descripcion: 'Descongelamiento',
    causas: ['Ciclo de deshielo activo'],
    solucion: 'No es una falla. Esperar a que termine el ciclo de descongelamiento.',
  },
  {
    codigo: 'FC',
    descripcion: 'Enfriamiento forzado',
    causas: ['Modo de servicio o enfriamiento forzado activo'],
    solucion: 'No es una falla. Salir del modo forzado según el procedimiento del modelo.',
  },
  {
    codigo: 'SC',
    descripcion: 'Autolimpieza',
    causas: ['Función Self Clean activa'],
    solucion: 'No es una falla. Esperar a que finalice la autolimpieza.',
  },
  {
    codigo: 'CP',
    descripcion: 'Control remoto desactivado o función asociada',
    causas: ['Función o estado de operación activo según la plataforma'],
    solucion: 'No necesariamente es una falla. Confirmar la función en el manual del modelo y habilitar el control remoto si corresponde.',
  },
  {
    codigo: 'DE',
    descripcion: 'Señal de entrada DR',
    causas: ['Entrada DR activa o configuración del modelo'],
    solucion: 'No necesariamente es una falla. Verificar la configuración de la entrada DR y el procedimiento del modelo si el estado permanece.',
  },
  {
    codigo: 'FP',
    descripcion: 'Calefacción para temperatura ambiente inferior a 8 °C',
    causas: ['Función de protección o calefacción activa'],
    solucion: 'No es una falla por sí mismo. Confirmar la temperatura ambiente y esperar o salir de la función según el manual.',
  },
  {
    codigo: 'LP',
    descripcion: 'Protección por baja temperatura ambiente',
    causas: ['Temperatura exterior por debajo del rango de funcionamiento'],
    solucion: 'Es un estado de protección. Verificar las condiciones ambientales y el rango permitido por el modelo.',
  },
  {
    codigo: 'NF',
    descripcion: 'Recordatorio de reemplazo o limpieza de filtro',
    causas: ['Mantenimiento programado'],
    solucion: 'No es una falla. Limpiar o reemplazar el filtro y reiniciar el recordatorio según el manual.',
    partes: ['Filtro de aire'],
  },
  {
    codigo: '--',
    descripcion: 'Conflicto de modo entre unidades interiores',
    causas: ['Unidades multizona solicitando modos incompatibles'],
    solucion: 'No es necesariamente una falla. Revisar que las unidades interiores del sistema multizona no estén solicitando frío y calor simultáneamente.',
  },
];