import type { EquipoTipo, FaultItem } from '@/types/diagnostico';

export const FALLAS_POR_EQUIPO: Record<EquipoTipo, FaultItem[]> = {
  nevera: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-noenfria', label: 'Congela pero no enfría', treeId: 'congela_noenfria', icon: 'snowflake' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  congelador: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-noenfria', label: 'Congela pero no enfría', treeId: 'congela_noenfria', icon: 'snowflake' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  nevecon: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-noenfria', label: 'Congela pero no enfría', treeId: 'congela_noenfria', icon: 'snowflake' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  minibar: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-noenfria', label: 'Congela pero no enfría', treeId: 'congela_noenfria', icon: 'snowflake' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  lavadora: [
    { id: 'nocentrifuga', label: 'No centrifuga',           treeId: 'nocentrifuga',           icon: 'rotate-cw' },
    { id: 'nodesagua',    label: 'No desagua',              treeId: 'nodesagua',              icon: 'arrow-down-circle' },
    { id: 'nollena',      label: 'No llena / No toma agua', treeId: 'nollena',                icon: 'arrow-up-circle' },
    { id: 'noenciende',   label: 'No enciende',             treeId: 'noenciende',             icon: 'power' },
    { id: 'error-e1',     label: 'Error E1 / E2 / F5',     treeId: 'errorelectronico_lavadora', icon: 'alert-circle' },
    { id: 'ruido',        label: 'Ruido / Vibración',       treeId: 'ruidoexcesivo',          icon: 'volume-2' },
    { id: 'fuga-agua',    label: 'Fuga de agua',            treeId: 'fuga_agua',              icon: 'droplet' },
    { id: 'nolavado',     label: 'No lava bien',            treeId: 'nolavado',               icon: 'x-circle' },
    { id: 'noseca',       label: 'No seca bien',            treeId: 'noseca',                 icon: 'wind' },
  ],
  secadora: [
    { id: 'noseca',       label: 'No seca bien',            treeId: 'noseca',                 icon: 'wind' },
    { id: 'noenciende',   label: 'No enciende',             treeId: 'noenciende',             icon: 'power' },
    { id: 'error-e1',     label: 'Error de secadora',       treeId: 'errorelectronico_lavadora', icon: 'alert-circle' },
    { id: 'ruido',        label: 'Ruido / Vibración',       treeId: 'ruidoexcesivo',          icon: 'volume-2' },
    { id: 'fuga-agua',    label: 'Fuga de agua',            treeId: 'fuga_agua',              icon: 'droplet' },
  ],
  aire: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  dispensadores: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  vitrina: [
    { id: 'congela-noenfria', label: 'Congela pero no enfría', treeId: 'congela_noenfria', icon: 'snowflake' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
  ],
  otro: [
    { id: 'noenfria',       label: 'No enfría',               treeId: 'noenfria',          icon: 'thermometer' },
    { id: 'congela-mucho',  label: 'Congela demasiado',       treeId: 'congelamucho',      icon: 'alert-triangle' },
    { id: 'fuga-agua',      label: 'Fuga de agua',            treeId: 'fuga_agua',         icon: 'droplet' },
    { id: 'noarranque',     label: 'Compresor no arranca',    treeId: 'noarranque',        icon: 'zap-off' },
    { id: 'ruido',          label: 'Ruido excesivo',          treeId: 'ruidoexcesivo',     icon: 'volume-2' },
    { id: 'error-el',       label: 'Error electrónico',       treeId: 'errorelectronico',  icon: 'cpu' },
    { id: 'escarcha',       label: 'Escarcha excesiva',       treeId: 'escarcha',          icon: 'cloud-snow' },
    { id: 'noenciende',     label: 'No enciende / Sin luz',   treeId: 'noenciende',        icon: 'power' },
    { id: 'alto-consumo',   label: 'Alto consumo eléctrico',  treeId: 'noenfria',          icon: 'activity' },
    { id: 'ventilador',     label: 'Ventilador no funciona',  treeId: 'ruidoexcesivo',     icon: 'wind' },
    { id: 'descongela',     label: 'Descongela alimentos',    treeId: 'noenfria',          icon: 'sun' },
    { id: 'display',        label: 'Display apagado',         treeId: 'errorelectronico',  icon: 'monitor' },
    { id: 'nodesagua',      label: 'No desagua',              treeId: 'nodesagua',         icon: 'arrow-down-circle' },
  ],
};

export function getFallas(tipo: EquipoTipo): FaultItem[] {
  return FALLAS_POR_EQUIPO[tipo] ?? [];
}
